# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43da10beb13600d028a18eef30086cd43b41ff8e63c79f3e377460ffa31ce28a930dc919bbfb3442b5e2405f1d2cbe5b91852ef7e5ee9f86c0dfa697eee33263

test:
  secret_key_base: 55ae4a0dbcdebfac0a4c6f577921f4c7e5a93da9bbfab9976a9cb154b60a10bd691f454a42cb17ab60565130ba91792ffa013c0d6df0fcd3cf01575af25a91a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
